[package]
name = "vigil-wayland"
description = "sctk session-lock glue, WlShm presenter, seat input for vigil-lock"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
slint-idle-runtime.workspace = true
span-lines.workspace = true
tracing.workspace = true
vigil-core.workspace = true
vigil-config.workspace = true
vigil-flow.workspace = true
smithay-client-toolkit.workspace = true
calloop-wayland-source.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-scanner.workspace = true
wayland-backend.workspace = true
