name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/release.yml@cda4f4fa38fc8142439665f0e2d1946bc37ac595
    secrets: inherit
    with:
      spec-name: vigil
      copr-project: vigil
      security: true
